name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      # Khởi chạy Pipeline khi có thay đổi trong các microservices
      - "auth-service/**"
      - "upload-service/**"
      - "ingestion-service/**"
      - "rag-service/**"
      - ".github/workflows/**"

env:
  PROJECT_ID: legal-chatbot-496302 # Hãy thay bằng Project ID thật của bạn
  REGION: asia-southeast1
  ENV: prod
  # Các biến dưới đây lấy từ kết quả lệnh `terraform apply` (phần Outputs)
  WIF_PROVIDER: "projects/1038257786675/locations/global/workloadIdentityPools/github-actions-pool-prod/providers/github-provider"
  CICD_SERVICE_ACCOUNT: "legal-rag-cicd-prod@legal-chatbot-496302.iam.gserviceaccount.com"
  APP_SERVICE_ACCOUNT: "legal-rag-app-prod@legal-chatbot-496302.iam.gserviceaccount.com"

jobs:
  build-and-deploy:
    name: Deploy Microservices
    runs-on: ubuntu-latest

    # Rất quan trọng để thiết lập id-token: write cho Workload Identity Federation
    permissions:
      contents: "read"
      id-token: "write"

    strategy:
      matrix:
        # Cấu hình tự động build và deploy nhiều services song song
        service:
          - auth-service
          - upload-service
          - ingestion-service
          - rag-service

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Google Auth (Workload Identity Federation)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ env.WIF_PROVIDER }}"
          service_account: "${{ env.CICD_SERVICE_ACCOUNT }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Docker Auth to Artifact Registry
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |-
          # Định nghĩa tên image
          IMAGE_NAME="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/legal-rag-repo-${{ env.ENV }}/${{ matrix.service }}:${{ github.sha }}"

          # Di chuyển vào thư mục của service
          cd ${{ matrix.service }}

          # Build image
          docker build -t $IMAGE_NAME .

          # Push image lên Artifact Registry
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: "${{ matrix.service }}-${{ env.ENV }}"
          region: "${{ env.REGION }}"
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/legal-rag-repo-${{ env.ENV }}/${{ matrix.service }}:${{ github.sha }}"
          flags: >-
            --allow-unauthenticated
            --service-account=${{ env.APP_SERVICE_ACCOUNT }}

      - name: Show Output URL
        run: echo "Deployed ${{ matrix.service }} to ${{ steps.deploy.outputs.url }}"
